# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Organiza' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Organiza
pod 'Firebase'
pod 'Firebase/Database'
end
